//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterTradingWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
            this.TRANSACTIONs1 = new HashSet<TRANSACTION>();
        }
    
        public int productID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string qty { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> userID { get; set; }
        public string x { get; set; }
        public string y { get; set; }
        public string quality { get; set; }
        public string imageURL { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONs1 { get; set; }
    }
}
