//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterTradingWebServices
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
            this.TRANSACTIONs1 = new HashSet<TRANSACTION>();
        }

        [DataMember(Order = 1)]
        public int productID { get; set; }
        [DataMember(Order = 2)]
        public string name { get; set; }
        [DataMember(Order = 3)]
        public string description { get; set; }
        [DataMember(Order = 4)]
        public string qty { get; set; }
        [DataMember(Order = 5)]
        public Nullable<int> status { get; set; }
        [DataMember(Order = 6)]
        public Nullable<int> userID { get; set; }
        [DataMember(Order = 7)]
        public string x { get; set; }
        [DataMember(Order = 8)]
        public string y { get; set; }
        [DataMember(Order = 9)]
        public string quality { get; set; }
        [DataMember(Order = 10)]
        public string imageURL { get; set; }

        [DataMember(Order = 11)]    
        public virtual USER USER { get; set; }
        [DataMember(Order = 12)]
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
        [DataMember(Order = 13)]
        public virtual ICollection<TRANSACTION> TRANSACTIONs1 { get; set; }
    }
}
