//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterTradingWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int transactionID { get; set; }
        public int productOfferID { get; set; }
        public int productTakeID { get; set; }
        public string status { get; set; }
        public int userOfferID { get; set; }
        public int userTakeID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
