//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterTradingWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
            this.TRANSACTIONs1 = new HashSet<TRANSACTION>();
            this.WISHes = new HashSet<WISH>();
        }
    
        public int userID { get; set; }
        public string password { get; set; }
        public string nickname { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string dob { get; set; }
        public string sex { get; set; }
        public string imageURL { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONs1 { get; set; }
        public virtual ICollection<WISH> WISHes { get; set; }
    }
}
