//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterTradingWebServices
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class USER
    {
        public USER()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
            this.TRANSACTIONs1 = new HashSet<TRANSACTION>();
            this.WISHes = new HashSet<WISH>();
        }

        [DataMember(Order = 1)]
        public int userID { get; set; }
        [DataMember(Order = 2)]
        public string password { get; set; }
        [DataMember(Order = 3)]
        public string nickname { get; set; }
        [DataMember(Order = 4)]
        public string email { get; set; }
        [DataMember(Order = 5)]
        public string contact { get; set; }
        [DataMember(Order = 6)]
        public string dob { get; set; }
        [DataMember(Order = 7)]
        public string sex { get; set; }
        [DataMember(Order = 8)]
        public string imageURL { get; set; }
        [DataMember(Order = 9)]
        public string status { get; set; }

        [DataMember(Order = 10)]
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
        [DataMember(Order = 11)]
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
        [DataMember(Order = 12)]
        public virtual ICollection<TRANSACTION> TRANSACTIONs1 { get; set; }
        [DataMember(Order = 13)]
        public virtual ICollection<WISH> WISHes { get; set; }
    }
}
