//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterTradingWebServices
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class WISH
    {
        [DataMember(Order = 1)]
        public int wishID { get; set; }
        [DataMember(Order = 2)]
        public string name { get; set; }
        [DataMember(Order = 3)]
        public string status { get; set; }
        [DataMember(Order = 4)]
        public Nullable<int> userID { get; set; }

        [DataMember(Order = 5)]
        public virtual USER USER { get; set; }
    }
}
