//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterTradingWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class WISH
    {
        public int wishID { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
